branches:
  only:
    - master

install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install latexmk texlive texlive-xetex texlive-latex-extra texlive-math-extra texlive-fonts-extra

notifications:
  email: false

script:
  - latexmk -xelatex thesis
