branches:
  only:
    - master

install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install latexmk texlive texlive-xetex texlive-latex-extra texlive-math-extra texlive-fonts-extra

notifications:
  email: false

script:
#  - latexmk -pdf -e '$pdflatex=q/xelatex %O %S/' thesis.tex

deploy:
  provider: releases
  api_key: "34305b7b08fcc5d4b746bef87edd8588f05d7b72"
  file: "thesis.pdf"
  skip_cleanup: true
  on:
    tags: true
